
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rey
 */
public class Statistika_Form extends javax.swing.JFrame {

    /**
     * Creates new form Statistika_Form
     */
    DecimalFormat df = new DecimalFormat("#.###");
    public Statistika_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        data_tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jumlah_isi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sig_x = new javax.swing.JLabel();
        sig_y = new javax.swing.JLabel();
        sig_xy = new javax.swing.JLabel();
        sig_xx = new javax.swing.JLabel();
        sig_yy = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        persamaan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        data_tabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        data_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"2",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"3",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"4",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"5",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"6",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"7",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"8",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"9",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"10",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"11",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"12",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"13",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"14",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"15",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"16",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"17",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"18",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"19",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)},
                {"20",  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0),  new Integer(0)}
            },
            new String [] {
                "No.", "X", "Y", "XY", "X^2", "Y^2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        data_tabel.setName("data_tabel"); // NOI18N
        jScrollPane1.setViewportView(data_tabel);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Hitung");
        jButton1.setName("btn_hitung"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Jumlah data (N)");

        jumlah_isi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jumlah_isi.setText("0");
        jumlah_isi.setName("jumlah_isi"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ΣX");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("ΣY");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText(":");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText(":");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("ΣXY");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ΣX^2");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("ΣY^2");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText(":");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText(":");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText(":");

        sig_x.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sig_x.setText("0");
        sig_x.setName("sig_x"); // NOI18N

        sig_y.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sig_y.setText("0");
        sig_y.setName("sig_y"); // NOI18N

        sig_xy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sig_xy.setText("0");
        sig_xy.setName("sig_xy"); // NOI18N

        sig_xx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sig_xx.setText("0");
        sig_xx.setName("sig_xx"); // NOI18N

        sig_yy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sig_yy.setText("0");
        sig_yy.setName("sig_yy"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Hasil Persamaan :");

        persamaan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        persamaan.setName("persamaan"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jumlah_isi))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sig_x)
                                    .addComponent(sig_y))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(sig_yy))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(sig_xx))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(87, 87, 87)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(sig_xy)))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addComponent(jLabel10)
                            .addComponent(persamaan))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jumlah_isi)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(sig_xy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(sig_x)
                    .addComponent(sig_xx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(sig_y)
                    .addComponent(sig_yy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(persamaan)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int jml_x, jml_y, jml_xy, jml_xx, jml_yy, jml_data;
        double persamaan_a, persamaan_b;
        jml_x = 0;
        jml_y = 0;
        jml_xy = 0;
        jml_xx = 0;
        jml_yy = 0;
        jml_data = 0;

        data_tabel.setValueAt(hitung(0, 1), 0, 3);
        data_tabel.setValueAt(hitung(0, 2), 0, 4);
        data_tabel.setValueAt(hitung(0, 3), 0, 5);

        data_tabel.setValueAt(hitung(1, 1), 1, 3);
        data_tabel.setValueAt(hitung(1, 2), 1, 4);
        data_tabel.setValueAt(hitung(1, 3), 1, 5);

        data_tabel.setValueAt(hitung(2, 1), 2, 3);
        data_tabel.setValueAt(hitung(2, 2), 2, 4);
        data_tabel.setValueAt(hitung(2, 3), 2, 5);

        data_tabel.setValueAt(hitung(3, 1), 3, 3);
        data_tabel.setValueAt(hitung(3, 2), 3, 4);
        data_tabel.setValueAt(hitung(3, 3), 3, 5);

        data_tabel.setValueAt(hitung(4, 1), 4, 3);
        data_tabel.setValueAt(hitung(4, 2), 4, 4);
        data_tabel.setValueAt(hitung(4, 3), 4, 5);

        data_tabel.setValueAt(hitung(5, 1), 5, 3);
        data_tabel.setValueAt(hitung(5, 2), 5, 4);
        data_tabel.setValueAt(hitung(5, 3), 5, 5);

        data_tabel.setValueAt(hitung(6, 1), 6, 3);
        data_tabel.setValueAt(hitung(6, 2), 6, 4);
        data_tabel.setValueAt(hitung(6, 3), 6, 5);

        data_tabel.setValueAt(hitung(7, 1), 7, 3);
        data_tabel.setValueAt(hitung(7, 2), 7, 4);
        data_tabel.setValueAt(hitung(7, 3), 7, 5);

        data_tabel.setValueAt(hitung(8, 1), 8, 3);
        data_tabel.setValueAt(hitung(8, 2), 8, 4);
        data_tabel.setValueAt(hitung(8, 3), 8, 5);

        data_tabel.setValueAt(hitung(9, 1), 9, 3);
        data_tabel.setValueAt(hitung(9, 2), 9, 4);
        data_tabel.setValueAt(hitung(9, 3), 9, 5);

        data_tabel.setValueAt(hitung(10, 1), 10, 3);
        data_tabel.setValueAt(hitung(10, 2), 10, 4);
        data_tabel.setValueAt(hitung(10, 3), 10, 5);

        data_tabel.setValueAt(hitung(11, 1), 11, 3);
        data_tabel.setValueAt(hitung(11, 2), 11, 4);
        data_tabel.setValueAt(hitung(11, 3), 11, 5);

        data_tabel.setValueAt(hitung(12, 1), 12, 3);
        data_tabel.setValueAt(hitung(12, 2), 12, 4);
        data_tabel.setValueAt(hitung(12, 3), 12, 5);

        data_tabel.setValueAt(hitung(13, 1), 13, 3);
        data_tabel.setValueAt(hitung(13, 2), 13, 4);
        data_tabel.setValueAt(hitung(13, 3), 13, 5);

        data_tabel.setValueAt(hitung(14, 1), 14, 3);
        data_tabel.setValueAt(hitung(14, 2), 14, 4);
        data_tabel.setValueAt(hitung(14, 3), 14, 5);

        data_tabel.setValueAt(hitung(15, 1), 15, 3);
        data_tabel.setValueAt(hitung(15, 2), 15, 4);
        data_tabel.setValueAt(hitung(15, 3), 15, 5);

        data_tabel.setValueAt(hitung(16, 1), 16, 3);
        data_tabel.setValueAt(hitung(16, 2), 16, 4);
        data_tabel.setValueAt(hitung(16, 3), 16, 5);

        data_tabel.setValueAt(hitung(17, 1), 17, 3);
        data_tabel.setValueAt(hitung(17, 2), 17, 4);
        data_tabel.setValueAt(hitung(17, 3), 17, 5);

        data_tabel.setValueAt(hitung(18, 1), 18, 3);
        data_tabel.setValueAt(hitung(18, 2), 18, 4);
        data_tabel.setValueAt(hitung(18, 3), 18, 5);

        data_tabel.setValueAt(hitung(19, 1), 19, 3);
        data_tabel.setValueAt(hitung(19, 2), 19, 4);
        data_tabel.setValueAt(hitung(19, 3), 19, 5);

        for (int i = 0; i < 20; i++) {
            if ((int) data_tabel.getValueAt(i, 1) != 0 && (int) data_tabel.getValueAt(i, 2) != 0) {
                jml_x = jml_x + (int) data_tabel.getValueAt(i, 1);
                jml_y = jml_y + (int) data_tabel.getValueAt(i, 2);
                jml_xy = jml_xy + (int) data_tabel.getValueAt(i, 3);
                jml_xx = jml_xx + (int) data_tabel.getValueAt(i, 4);
                jml_yy = jml_yy + (int) data_tabel.getValueAt(i, 5);
                jml_data++;
            }
        }

//        data_tabel.setValueAt(jml_x, 20, 1);
//        data_tabel.setValueAt(jml_y, 20, 2);
//        data_tabel.setValueAt(jml_xy, 20, 3);
//        data_tabel.setValueAt(jml_xx, 20, 4);
//        data_tabel.setValueAt(jml_yy, 20, 5);
        
        jumlah_isi.setText(String.valueOf(jml_data));
        sig_x.setText(String.valueOf(jml_x));
        sig_y.setText(String.valueOf(jml_y));
        sig_xy.setText(String.valueOf(jml_xy));
        sig_xx.setText(String.valueOf(jml_xx));
        sig_yy.setText(String.valueOf(jml_yy));
        
        persamaan_a = (((double) jml_y*(double) jml_xx)-((double) jml_x*(double) jml_xy))/(((double) jml_data*(double) jml_xx)-((double) jml_x*(double) jml_x));
        persamaan_b = (((double) jml_data*(double) jml_xy)-((double) jml_x*(double) jml_y))/(((double) jml_data*(double) jml_xx)-((double) jml_x*(double) jml_x));
        
        persamaan.setText("Y = " + df.format(persamaan_a) + "a + (" + df.format(persamaan_b) + "b)");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Statistika_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Statistika_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Statistika_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Statistika_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Statistika_Form().setVisible(true);
            }
        });
    }

    public static int hitung(int baris, int param) {
        int a, b, c;
        a = (int) data_tabel.getValueAt(baris, 1);
        b = (int) data_tabel.getValueAt(baris, 2);
        c = 0;

        if (param == 1) {
            c = a * b;
        } else if (param == 2) {
            c = a * a;
        } else if (param == 3) {
            c = b * b;
        }
        return c;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable data_tabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jumlah_isi;
    private javax.swing.JLabel persamaan;
    private javax.swing.JLabel sig_x;
    private javax.swing.JLabel sig_xx;
    private javax.swing.JLabel sig_xy;
    private javax.swing.JLabel sig_y;
    private javax.swing.JLabel sig_yy;
    // End of variables declaration//GEN-END:variables
}
